language: php
dist: focal
php:
  - '8.1.0'
env:
  - DB_NAME=test DB_USER=travis DB_PASS= DB_HOST=127.0.0.1
  global:
    - XDEBUG_MODE=coverage
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
   - composer install
   - composer require --dev phpunit/phpunit ^9
   - composer require --dev php-coveralls/php-coveralls
   - vendor/bin/phpunit tests/
after_success:
  - travis_retry php vendor/bin/php-coveralls
