language: php
php:
  - '8.1'
env:
  - DB_NAME=test DB_USER=travis DB_PASS= DB_HOST=127.0.0.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
   - composer install
   - composer require --dev phpunit/phpunit ^9
   - vendor/bin/phpunit tests/
